#!/usr/bin/env python3
"""
gen_web_data.py - Convert HTML files to C const unsigned char arrays.

Usage:
    python gen_web_data.py <pages_dir> <output_c_file>

Input:  pages_dir/*.html  (one file per page)
Output: C file with const unsigned char arrays, one per HTML file.
"""

import os
import re
import sys

def escape_char(b):
    """Format a single byte as a C hex literal."""
    return f"0x{b:02X}"

def generate(pages_dir, output_file):
    html_files = sorted([
        f for f in os.listdir(pages_dir) if f.endswith(".html")
    ])

    if not html_files:
        print("No .html files found in", pages_dir)
        sys.exit(1)

    lines = []
    lines.append("/* Auto-generated by gen_web_data.py - do not edit */")
    lines.append("")

    for fname in html_files:
        var_name = os.path.splitext(fname)[0]  # e.g. wifisetting
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", var_name):
            print(f"Invalid HTML file name for C symbol: {fname}")
            sys.exit(1)

        filepath = os.path.join(pages_dir, fname)
        with open(filepath, "rb") as f:
            data = f.read()

        lines.append(f"const unsigned char {var_name}[{len(data)}] = {{")

        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_bytes = ", ".join(escape_char(b) for b in chunk)
            lines.append(f"  {hex_bytes},")

        lines.append("};")
        lines.append("")

    with open(output_file, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {output_file}: {len(html_files)} pages, "
          f"{sum(1 for l in lines if l.startswith('const unsigned char'))} arrays")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: gen_web_data.py <pages_dir> <output_c_file>")
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
